boost: fix fiber header (#47540)
include/boost/fiber/detail/context_spmc_queue.hpp:1:1: error: stray ‘\357’ in program
caused by a leftover UTF-8 Byte Order Mark