Fix Nixpkgs evaluation
error: attribute `luaversion' missing, at /home/eelco/Dev/nixpkgs/pkgs/development/interpreters/lua-5/expat.nix:16:34
(cherry picked from commit af69fcde47774876588fbf61179ca0e55fa69eac)