swift: pin to use clang5, build failure w/clang7
Error:

    FAILED: tools/swift-reflection-dump/CMakeFiles/swift-reflection-dump.dir/swift-reflection-dump.cpp.o
    /nix/store/mp36qs9cgzghraddzx68pwxvi0xzb77c-clang-wrapper-7.0.0/bin/clang++  -DCMARK_STATIC_DEFINE -DGTEST_HAS_RTTI=0 -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/swift-reflection-dump -I/build/src/swift/tools/swift-reflection-dump -Iinclude -I/build/src/swift/include -I/build/src/llvm/include -I/build/build/buildbot_linux/llvm-linux-x86_64/include -I/build/build/buildbot_linux/llvm-linux-x86_64/tools/clang/include -I/build/src/llvm/tools/clang/include -I/build/src/cmark/src -I/build/build/buildbot_linux/cmark-linux-x86_64/src -Wno-unknown-warning-option -Werror=unguarded-availability-new -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fcolor-diagnostics -ffunction-sections -fdata-sections -Werror=switch -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -O3    -UNDEBUG  -fno-exceptions -fno-rtti -target x86_64-unknown-linux-gnu -O2 -g0 -UNDEBUG -MD -MT tools/swift-reflection-dump/CMakeFiles/swift-reflection-dump.dir/swift-reflection-dump.cpp.o -MF tools/swift-reflection-dump/CMakeFiles/swift-reflection-dump.dir/swift-reflection-dump.cpp.o.d -o tools/swift-reflection-dump/CMakeFiles/swift-reflection-dump.dir/swift-reflection-dump.cpp.o -c /build/src/swift/tools/swift-reflection-dump/swift-reflection-dump.cpp
    In file included from /build/src/swift/tools/swift-reflection-dump/swift-reflection-dump.cpp:23:
    In file included from /build/src/swift/include/swift/Reflection/ReflectionContext.h:29:
    /build/src/swift/include/swift/Reflection/TypeRef.h:192:5: error: 'BuiltinTypeRefs' following the 'template' keyword does not refer to a template
        FIND_OR_CREATE_TYPEREF(A, BuiltinTypeRef, MangledName);
        ^
    /build/src/swift/include/swift/Reflection/TypeRef.h:51:51: note: expanded from macro 'FIND_OR_CREATE_TYPEREF'
      const auto Entry = Allocator.DEPENDENT_TEMPLATE TypeRefTy##s.find(ID);       \
                                                      ^
    <scratch space>:57:1: note: expanded from here
    BuiltinTypeRefs
    ^
    /build/src/swift/include/swift/Reflection/TypeRefBuilder.h:209:28: note: in instantiation of function template specialization 'swift::reflection::BuiltinTypeRef::create<swift::reflection::TypeRefBuilder>' requested here
        return BuiltinTypeRef::create(*this, mangledName);
                               ^
    /build/src/swift/include/swift/Reflection/TypeRefs.def:19:1: note: declared as a non-template here
    TYPEREF(Builtin, TypeRef)
    ^
    /build/src/swift/include/swift/Reflection/TypeRefBuilder.h:191:57: note: expanded from macro 'TYPEREF'
                         TypeRefID::Hash, TypeRefID::Equal> Id##TypeRefs;
                                                            ^
    <scratch space>:35:1: note: expanded from here
    BuiltinTypeRefs
    ^
    In file included from /build/src/swift/tools/swift-reflection-dump/swift-reflection-dump.cpp:23:
    In file included from /build/src/swift/include/swift/Reflection/ReflectionContext.h:29:
    /build/src/swift/include/swift/Reflection/TypeRef.h:192:5: error: 'BuiltinTypeRefs' following the 'template' keyword does not refer to a template
        FIND_OR_CREATE_TYPEREF(A, BuiltinTypeRef, MangledName);
        ^

....and so on