Revert "fontforge: 20170730 -> 20190127 (untagged, latest git)"
lilypond breaks for w/e reason, gets confused about version:

>  ERROR: Please install required programs:  /nix/store/n7ql7fph3cidxm356hl0ak6zgrhf1mxv-fontforge-20190127/bin/fontforge >= 20110222 (installed: 20190127)

This reverts commit b8d3cb57e95f21b5ea26aae20fcfd894a49dd0f8.